const types = {
  GET_USER_LOGIN: "GET_USER_LOGIN",
  POST_DOCTOR: "POST_DOCTOR",
  GET_SPECIALITIES: "GET_SPECIALITIES",
  POST_PATIENT: "POST_PATIENT",
  GET_HEALTHINSURANCES: "GET_HEALTHINSURANCES",
  GET_MY_DOCTORS: "GET_MY_DOCTORS",
  GET_MY_PATIENTS: "GET_MY_PATIENTS",
  SAVE_NOTIFICATION: "SAVE_NOTIFICATION",
  GET_DOCTORS: "GET_DOCTORS",
  POST_MY_DOCTOR: "POST_MY_DOCTOR",
  // VER, SI NO SE USA, BORRARLA
  FILTER_SPECIALITIES: "FILTER_SPECIALITIES",
  FILTER_SPECIALITIES_MY_DOCTORS: "FILTER_SPECIALITIES_MY_DOCTORS",
  FILTER_SPECIALITIES_ALL_DOCTORS: "FILTER_SPECIALITIES_ALL_DOCTORS",
  FILTER_DOCTORS_BY_NAME: "FILTER_DOCTORS_BY_NAME",
  FILTER_MY_DOCTORS_BY_NAME: "FILTER_MY_DOCTORS_BY_NAME",
  DELETE_DOCTOR: "DELETE_DOCTOR",
  GET_NOTIFICATIONS: "GET_NOTIFICATIONS",
  DELETE_NOTIFICATIONS: "DELETE_NOTIFICATIONS",
  REJECT_NOTIFICATION: "REJECT_NOTIFICATION",
};
export default types;
