const types = {
  GET_USER_LOGIN: "GET_USER_LOGIN",
  POST_DOCTOR: "POST_DOCTOR",
  GET_SPECIALITIES: "GET_SPECIALITIES",
  POST_PATIENT: "POST_PATIENT",
  GET_HEALTHINSURANCES: "GET_HEALTHINSURANCES",
  GET_MY_DOCTORS: "GET_MY_DOCTORS",
  SAVE_NOTIFICATION: "SAVE_NOTIFICATION",
  GET_DOCTORS: "GET_DOCTORS",
};
export default types;
