const types = {
  GET_USER_LOGIN: "GET_USER_LOGIN",
  POST_DOCTOR: "POST_DOCTOR",
  POST_PATIENT: "POST_PATIENT",
  GET_HEALTHINSURANCES: "GET_HEALTHINSURANCES"
  SAVE_NOTIFICATION: "SAVE_NOTIFICATION"
};
export default types;
